export const GET_CONTENT_CREDENTIALS_KEY = 'GET_CONTENT_CREDENTIALS';
export const GET_CONTENT_CREDENTIAL_KEY = 'GET_CONTENT_CREDENTIAL';
export const UPDATE_CONTENT_CREDENTIAL_KEY = 'UPDATE_CONTENT_CREDENTIAL';
export const DELETE_CONTENT_CREDENTIAL_KEY = 'DELETE_CONTENT_CREDENTIAL';
export const CONTENT_CREDENTIAL_CERT_TYPE = 'cert';
